cs_main:
    resource: "@CSMainBundle/Resources/config/routing.yml"
    prefix:   /

salex_user:
    resource: "@SalexUserBundle/Controller/"
    type:     annotation


avanzu_admin:
    resource: "@AvanzuAdminThemeBundle/Resources/config/routes.yml"
    
#FOSUserBundle routing file
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

# image processing bundle
# https://github.com/liip/LiipImagineBundle
_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

avanzu_admin_profile:
    path: /profile

jmose_command_scheduler:
    resource: "@JMoseCommandSchedulerBundle/Resources/config/routing.yml"
    prefix:   /
