<?php

namespace CS\MainBundle\Repository;

/**
 * DesignationPartieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DesignationPartieRepository extends \Doctrine\ORM\EntityRepository
{
}
