<?php

namespace CS\MainBundle\Repository;

/**
 * ImmeublesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImmeublesRepository extends \Doctrine\ORM\EntityRepository
{
}
