<?php

namespace CS\MainBundle\Repository;

/**
 * LocationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocationsRepository extends \Doctrine\ORM\EntityRepository
{
    public function findActive()
    {
        $queryBuilder = $this
            ->createQueryBuilder('l')
            ->where('l.active = :a')
            ->setParameter('t.a', true)
        ;

        // On récupère la Query à partir du QueryBuilder
        $query = $queryBuilder->getQuery();

        // On récupère les résultats à partir de la Query
        $results = $query->getResult();

        return $results;

    }

}
