services:
    salex_user.resetting.form.type:
        class: SalexUserBundle\Form\ResettingFormType
        tags:
            - { name: form.type, alias: salex_user_resetting }

    salex_user.profile.form.type:
        class: SalexUserBundle\Form\UserType
        tags:
            - { name: form.type, alias: salex_user_profile }